import { ControlledRadioButtonsGroup } from "../../../../util/reuseableComponents/SelectCmp";

export const filtering = [
  {
    Name: "Cars",
    Brand: [
      "Toyota",
      "Hyundai",
      "Nissan",
      "Volkswagen",
      "Land Rover",
      "Ford",
      "Honda",
      "Lexus",
      "Mercedes-Benz",
      "Others",
    ],
    Condition: ["New", "Used"],
    Year_of_manufacture: generateArrayOfYears(),
    Transmission: ["Automatic", "Manual"],
    Is_registered: ["Yes", "No"],
    Colour: [
      "Black",
      "Blue",
      "White",
      "Grey",
      "Red",
      "Silver",
      "Green",
      "Yellow",
      "Brown",
      "Purple",
      "Others",
    ],
  },
  {
    Name: "Buses",
    Brand: [
      "Toyota",
      "Volkswagen",
      "Nissan",
      "Suzuki",
      "Ford",
      "Honda",
      "Mercedes-Benz",
      "Others",
    ],
    Condition: ["New", "Used"],
    Year_of_manufacture: generateArrayOfYears(),
    Transmission: ["Automatic", "Manual"],
    Is_registered: ["Yes", "No"],
    Colour: [
      "Black",
      "Blue",
      "White",
      "Grey",
      "Red",
      "Silver",
      "Green",
      "Yellow",
      "Brown",
      "Purple",
      "Others",
    ],
  },
  {
    Name: "Trucks and trailers",
    Type: [
      "Heavy Duty Trucks",
      "Dump Trucks",
      "Mini Truck",
      "Rigid Trucks",
      "Trailers",
      "Food Trucks",
      "Others",
    ],
    Brand: [
      "Toyota",
      "Volkswagen",
      "Nissan",
      "MAN",
      "Mack",
      "DAF",
      "Ford",
      "Volvo",
      "Mercedes-Benz",
      "Others",
    ],
    Condition: ["New", "Used"],
    Year_of_manufacture: generateArrayOfYears(),
    Transmission: ["Automatic", "Manual"],
    Is_registered: ["Yes", "No"],
    Colour: [
      "Black",
      "Blue",
      "White",
      "Grey",
      "Red",
      "Silver",
      "Green",
      "Yellow",
      "Brown",
      "Purple",
      "Others",
    ],
  },
  {
    Name: "Vehicle parts and accessories",
    Type: [
      "Audio Parts",
      "Breaks, Suspension and Sterring",
      "Engine and Drivetrain",
      "Car Care",
      "Exterior Accessories",
      "Interior Accessories",
      "Wheels and Parts",
      "Safety and Security",
      "Others",
    ],
    Brand: [
      "Toyota",
      "Nissan",
      "Lexus",
      "Honda",
      "Acura",
      "Mercedes-Benz",
      "Others",
    ],
    Condition: ["New", "Used"],
  },
  {
    Name: "Motocycles and bicycles",
    Type: ["Bicycle", "Motocycle", "Scooter", "Others"],
    Brand: ["TVS", "Yamaha", "Honda", "Qlink", "Bajaj", "Suzuki", "Others"],
    Year_of_manufacture: generateArrayOfYears(),
    Transmission: ["Automatic", "Manual"],
    Condition: ["New", "Used"],
    Colour: [
      "Black",
      "Blue",
      "White",
      "Grey",
      "Red",
      "Silver",
      "Green",
      "Yellow",
      "Brown",
      "Purple",
      "Others",
    ],
  },
  {
    Name: "Computers and laptops",
    Type: ["Desktop Computer", "Laptop"],
    Brand: [
      "HP",
      "Dell",
      "Apple",
      "Lenovo",
      "Asus",
      "Acer",
      "Microsoft",
      "Others",
    ],
    Condition: ["New", "Used"],
    Operating_system: ["Windows", "Linux", "MacOS", "Others"],
    Processor: ["Intel", "AMD", "Others"],
    Storage_capacity: [
      "128GB",
      "250GB",
      "256GB",
      "320GB",
      "500GB",
      "512GB",
      "1TB",
      "Others",
    ],
    Storage_type: ["HDD", "SSD", "Others"],
    Ram: ["2GB", "4GB", "8GB", "16GB", "32GB", "64GB", "Others"],
  },
  {
    Name: "Audio and music equipments",
    Type: [
      "Speakers",
      "Microphones",
      "Sound Systems",
      "Home Theater Systems",
      "Music Mixers",
      "Amplifiers",
      "Sound Monitors",
      "Others",
    ],
    Condition: ["New", "Used"],
  },
  {
    Name: "Computer accessories",
    Type: ["Adapters", "Keyboards", "Mice", "Batteries", "Cables", "Others"],
    Condition: ["New", "Used"],
  },
  {
    Name: "Tv and dvd equipments",
    Type: ["TVs", "DVDs", "Projector", "Others"],
    Condition: ["New", "Used"],
    Brand: [
      "Sony",
      "Samsung",
      "TCL",
      "Panasonic",
      "Toshiba",
      "Sharp",
      "LG",
      "Others",
    ],
  },
  {
    Name: "Electronic supplies",
    Condition: ["New", "Used"],
  },
  {
    Name: "Skincare",
    Type: [
      "Body Creams and Milks",
      "Face Creamand Gels",
      "Body Oils",
      "Body Wash and Soap",
      "Exfoliators",
      "Others",
    ],
    Gender: ["Male", "Female", "Unisex"],
    Condition: ["New", "Used"],
  },
  {
    Name: "Hair products",
    Gender: ["Male", "Female", "Unisex"],
    Condition: ["New", "Used"],
    Type: [
      "Hair Extensions and Wigs",
      "Shampoos",
      "Conditioners",
      "Hair Brushes and Combs",
      "Hair Treatments",
      "Others",
    ],
  },
  {
    Name: "Fragrances",
    Gender: ["Male", "Female", "Unisex"],
    Formation: ["Oil", "Spray"],
    Condition: ["New", "Used"],
  },
  {
    Name: "Vitamins and supplements",
    Type: [
      "Immune Boosters",
      "Vitamin Supplements",
      "Detox Cleansers",
      "Weight-Loss Products",
      "Energy Booters",
      "Anti-Aging Supplements",
      "Others",
    ],
    Formulation: ["Capsule", "Liquid", "Powder"],
    Condition: ["New", "Used"],
  },
  {
    Name: "Phones and tablets",
    Type: ["Phone", "Tablet"],
    Condition: ["New", "Used"],
    Storage_capacity: [
      "128GB",
      "250GB",
      "256GB",
      "320GB",
      "500GB",
      "512GB",
      "1TB",
      "Others",
    ],

    Colour: [
      "Black",
      "Blue",
      "White",
      "Grey",
      "Red",
      "Silver",
      "Green",
      "Yellow",
      "Brown",
      "Purple",
      "Others",
    ],
    Display_type: ["LCD", "IPS-LCD", "OLED", "AMOLED"],
    Ram: ["2GB", "4GB", "8GB", "16GB", "32GB", "64GB", "Others"],
    Brand: [
      "Apple",
      "Samsung",
      "Techno",
      "Itel",
      "Huawei",
      "Infinix",
      "Nokia",
      "Others",
    ],
  },
  {
    Type: [
      "Power Bank",
      "Cases",
      "Chargers and power adapters",
      "Phone screens",
      "Memory cards",
      "Others",
    ],
    Condition: ["New", "Used"],
    Name: "Accessories for mobile phones and tablets",
  },
  {
    Name: "Houses and apartments for rent",
    Condition: ["New", "Used"],
    Is_furnished: ["Yes", "Partially furnished", "No"],
    Has_parking_space: ["Yes", "No"],
    Bathrooms: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    Bedrooms: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    Type: [
      "Apartment",
      "Townhouse",
      "Block of Flats",
      "Duplex",
      "Bungalow",
      "Others",
    ],
  },
  {
    Name: "Houses and apartments for sale",
    Condition: ["New", "Used"],
    Has_parking_space: ["Yes", "No"],
    Is_furnished: ["Yes", "Partially furnished", "No"],
    Bathrooms: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    Bedrooms: ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10"],
    Type: [
      "Apartment",
      "Townhouse",
      "Block of Flats",
      "Duplex",
      "Bungalow",
      "Others",
    ],
  },
  {
    Name: "Land and plots for sale",
    Type: ["Commercial Land", "Farmland", "Residential Land", "Mixed-Use Land"],
    Number_of_plots: [
      "1",
      "2",
      "3",
      "4",
      "5",
      "6",
      "7",
      "8",
      "9",
      "10",
      "Others",
    ],
  },
  {
    Name: "Bags",
    Type: [
      "Luggage and travel Bags",
      "Handbags",
      "Shoulder Bags",
      "Backpacks",
      "Wallets and purses",
      "Others",
    ],
    Condition: ["New", "Used"],
    Gender: ["Male", "Female", "Unisex"],
    Colour: [
      "Black",
      "Blue",
      "White",
      "Grey",
      "Red",
      "Silver",
      "Green",
      "Yellow",
      "Brown",
      "Purple",
      "Others",
    ],
  },
  {
    Name: "Clothing and clothing accessories",
    Condition: ["New", "Used"],
    Type: [
      "Sunglasses",
      "Hats and Caps",
      "Belts",
      "Ties",
      "Trousers",
      "Shirts",
      "Sweaters",
      "Socks",
      "Others",
    ],
    Gender: ["Male", "Female", "Unisex"],
    Colour: [
      "Black",
      "Blue",
      "White",
      "Grey",
      "Red",
      "Silver",
      "Green",
      "Yellow",
      "Brown",
      "Purple",
      "Others",
    ],
  },
  {
    Name: "Watches",
    Brand: [
      "Rolex",
      "Hublot",
      "Patek Philippe",
      "Cartier",
      "Omega",
      "Audemars Piguet",
      "Others",
    ],
    Colour: [
      "Black",
      "Blue",
      "White",
      "Grey",
      "Red",
      "Silver",
      "Green",
      "Yellow",
      "Brown",
      "Purple",
      "Others",
    ],
    Gender: ["Male", "Female", "Unisex"],
    Condition: ["New", "Used"],
    Style: ["Business", "Casual", "Sport", "Others"],
    Display: ["Analog", "Digital"],
  },
  {
    Name: "Shoes",
    Brand: [
      "Adidas",
      "Gucci",
      "Louis Vuitton",
      "Nike",
      "Versace",
      "Air Jordan",
      "Others",
    ],
    Gender: ["Male", "Female", "Unisex"],
    Condition: ["New", "Used"],
    Type: [
      "Sneakers",
      "Slippers",
      "Flat shoes",
      "Sandals",
      "Slides",
      "Boots",
      "Others",
    ],
    Colour: [
      "Black",
      "Blue",
      "White",
      "Grey",
      "Red",
      "Silver",
      "Green",
      "Yellow",
      "Brown",
      "Purple",
      "Others",
    ],
    Style: ["Casual", "Classic", "Formal", "Sport", "Others"],
  },
];

function generateArrayOfYears() {
  const currentYear = new Date().getFullYear();
  //We want to go as far back as duration years ago
  const DURATION = 20;
  const startingYear = currentYear - DURATION;
  const years = [];
  for (let i = currentYear; i >= startingYear; i--) {
    years.push(i + "");
  }
  return years;
}
export function getFilteringInformation(subcategoryName) {
  return (
    filtering.find((subcategory) => subcategory.Name === subcategoryName) ||
    null
  );
}

export function getFilterForSubcategory(subcategoryName, setFilterOptions) {
  const result = [];
  const postDetails = getFilteringInformation(subcategoryName);

  Object.entries(postDetails).forEach(([filterName, filterValues]) => {
    if (Array.isArray(filterValues)) {
      result.push(
        <ControlledRadioButtonsGroup
          list={filterValues}
          title={filterName.replaceAll("_", " ")}
          setFilterOptions={setFilterOptions}
        />
      );
    }
  });

  return result;
}
