export const state = {
  formation: "",
  selectedSubcategory: "",
  amount: "",
  selectedCategory: "",
  productTitle: "",
  transmission: "",
  isFurnished: "",
  selectedImages: [],
  productDescription: "",
  condition: "",
  model: "",
  processor: "",
  numberOfPlots: "",
  formulation: "",
  brand: "",
  yearOfManufacture: 0,
  ram: "",
  storageType: "",
  subCategories: [],
  colour: "",
  gender: "",
  bedrooms: "",
  isRegistered: "",
  displayType: "",
  display: "",
  showSnackbarCmp: null,
};
